services:
  backend:
    build:
      context: .
      target: prod
    restart: always
    ports:
      - 5000:5000
    env_file:
      - ./.env
      - ./.mongodb.env
    depends_on: 
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
      - ./.mongodb.env
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
