services:
  backend-dev:
    build:
      context: .
      target: build
    restart: always
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env
      - ./.mongodb.env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5000:5000
    command: npm run dev
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
      - ./.mongodb.env
    volumes:
      - mongo-db-dev:/data/db

volumes:
  mongo-db-dev:
